bcgov/sso-keycloak

- helm/keycloak/values-c6af30-dev.yaml
- helm/patroni/values-c6af30-dev-sso-patroni.yaml
These helm charts are not running.  These are the steps I took to deploy these charts to try and deploy keycloak.  I'm not clear on what's going wrong.
make uninstall NAME=sso-patroni NAMESPACE=c6af30-dev
helm delete sso-patroni
kubectl delete pvc -l release=sso-patroni
kubectl delete configmaps -l release=sso-patroni
make uninstall NAMESPACE=c6af30-dev
make create-random-db-secret NAME=sso-patroni NAMESPACE=c6af30-dev
make install NAME=sso-patroni NAMESPACE=c6af30-dev
make install NAMESPACE=c6af30-dev
> feat: patroni

- scripts/README.md
Add a warning to the deletion readme as a precaution.
As discussed in last week's ops meeting I've put an extra step in the deletion of custom realms to help prevent us from removing a realm that's in use.
> chore: document

- .github/workflows/publish-image-backup-storage-gold.yml
- docker/backup-container/Dockerfile
- docker/backup-container/backup.postgres.plugin
- helm/backup-storage/values-c6af30-dev-sso-backup.yaml
- helm/backup-storage/values-c6af30-test-sso-backup.yaml
- helm/backup-storage/values-eb75ad-dev-sso-backup.yaml
- helm/backup-storage/values-eb75ad-prod-sso-backup.yaml
- helm/backup-storage/values-eb75ad-test-sso-backup.yaml
- add an extra step to remove custom schemas generated by patroni `metric_helpers` and `user_management`
(https://github.com/bcgov/sso-keycloak/blob/chore/terraform/docker/backup-container/backup.postgres.plugin#L80)
- disable verification step in backup containers
> chore: override postgres back behaviour to dorp schemas

- .github/workflows/set-dr-active.yml
- helm/keycloak/transition-scripts/deploy-golddr-active.sh
- helm/keycloak/transition-scripts/set-patroni-dr-active.sh
- helm/keycloak/transition-values/set-dr-to-active-c6af30-test.yaml
- helm/keycloak/values-golddr-c6af30-test.yaml
This action allows us to trigger dr to become active in sandbox test.  
I want to get the 'set active to standby action working before I extend this to the production dr namespaces.
> Set gold DR to active

- .pre-commit-config.yaml
- docker/kc-cron-job/active-sessions.js
- helm/kc-cron-job/templates/cron-active-sessions.yaml
This PR adds the client ID to the database active sessions.  
The collumn 'client_id' was manually added to the gold sandbox, gold prod, and silver prod using:
`ALTER TABLE active_sessions ADD client_id varchar(1000);`
Next time the cron job is triggered the active sessions will have a client id
Note anything before today will have a null client_id
> feat: addclient

- docs/log-output-guide.md
This documents how to turn the relevant logging a request dumping on.
> chore: logdoc

- docker/keycloak/extensions-7.6/services/src/main/java/com/github/bcgov/keycloak/protocol/oidc/ext/endpoints/LegacyEndpoint.java
- docker/keycloak/extensions-7.6/services/src/main/resources/META-INF/services/org.keycloak.protocol.oidc.ext.OIDCExtProviderFactory
- This separate endpoint parses the query params and regenerates them to redirect back to the OIDC logout endpoint.
> feat: support oidc legacy logout endpoint

- helm/keycloak/README.md
- helm/keycloak/templates/route.yaml
- helm/keycloak/values-3d5c3f-prod.yaml
- helm/keycloak/values-6d70e7-prod.yaml
- helm/keycloak/values.yaml
- sandbox has been upgraded to more closely resemble silver prod (for future load testing)
- The timeout is added to the annotation making sure we can easily increase it (if only this changes the keycloak pods don't cycle)
- The default null ensures the other deployments in silver are unnafected by this change
> Bump annotation

- docker/keycloak/extensions-7.6/services/src/main/java/com/github/bcgov/keycloak/authenticators/CookieStopAuthenticator.java
handle two edge cases
- `kc_idp_hint` is invalid e.g. empty string
- identity provider alias does not exist
> chore: handle invalid kc_idp_hint

- .github/workflows/pre-commit.yml
- .github/workflows/publish-image-backup-storage-test.yml
- .github/workflows/publish-image-kc-cron-job.yml
- docker/keycloak/extensions-7.6/services/pom.xml
- docker/keycloak/extensions-7.6/services/src/main/java/com/github/bcgov/keycloak/authenticators/browser/IdentityProviderStopForm.java
- docker/keycloak/extensions-7.6/themes/src/main/resources/theme/base/admin/resources/partials/realm-identity-provider-oidc-ext.html
- docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov-idp-stopper/login/login.ftl
- docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov-idp-stopper/login/theme.properties
- docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov-no-header-no-footer/login/theme.properties
- docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov/login/resources/css/styles.css
- docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov/login/resources/js/script.js
- docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov/login/template.ftl
- docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov/login/theme.properties
- helm/keycloak/values-b861c7-test-4.yaml
- helm/keycloak/values-b861c7-test-5.yaml
- helm/keycloak/values-b861c7-test-6.yaml
- add an option in the `identify provider` configuration page to display tooltips in the login page
- update and create two `bcgov` themes that can be used for custom realms
- bump deprecated GitHub action versions
> feat: add optional tooltips for idp selections

- docker/keycloak/Dockerfile-7.6
- docker/keycloak/configuration/standalone-openshift-7.6.xml
- docker/keycloak/extensions-7.6/services/src/main/java/com/github/bcgov/keycloak/authenticators/CookieStopAuthenticator.java
- scripts/restore-idir-users-with-roles.js
- Updating the keycloak dockerfile to use [SSO 7.6-25](https://catalog.redhat.com/software/containers/rh-sso-7/sso76-openshift-rhel8/629651e2cddbbde600c0a2ec)
- Rolling back the fix added for [SSOTEAM-608](https://bcdevex.atlassian.net/browse/SSOTEAM-608)
- Adding a script to restore users that are deleted by [remove-inactive-idir-users](https://github.com/bcgov/sso-keycloak/blob/dev/docker/kc-cron-job/remove-inactive-idir-users.js)
> feat: sso security patch through 7.6-25

- docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov/login/messages/messages_en.properties
- docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov/login/resources/js/script-20221128.js
Below errors are customized:
1. differentUserAuthenticated
2. invalidFederatedIdentityActionMessage
Fixes [SSOTEAM-697](https://bcdevex.atlassian.net/browse/SSOTEAM-697)
> feat: custom messages for two login errors

- .github/workflows/unit-test.yaml
- .github/workflows/unit-test.yml
- docker/kc-cron-job/.dockerignore
- docker/kc-cron-job/README.md
- docker/kc-cron-job/__tests__/zip-logs.test.js
- docker/kc-cron-job/event-logs.js
- docker/kc-cron-job/jest.config.js
- docker/kc-cron-job/package.json
- docker/kc-cron-job/yarn.lock
Fix for an issue where kc-cron-job pod was hanging indefinitely. It was difficult to say exactly what triggered the error,  but it was caused by the promise wrapper of lineReader.close (event-logs.js line 61 in this pr) missing a rejection on error, so it just hung indefinitely, I could reproduce the exact same output triggering an error there. 
An error can trigger there when inserting a log that was in an unexpected format, e.g a blank line or it's missing expected keys. I added error handling around that so it won't hang indefinitely, and will log out the error and problem log going forward. 
I also added some additional checks in the log formatter to see if the JSON parse is failing, or some logs have a different set of keys than is expected. I added a unit test for malformed logs and …
> Fix: kc-cron-job hanging

- docker/kc-cron-job/Dockerfile
change to alpine node
I ran the built docker image locally for the zip-logs and dependencies are installing fine on alpine
> chore: version

- helm/kc-cron-job/migration.sql
wrap sql migration in a transaction to prevent conflicting function creation error (see ticket 1184 for details).
> chore: migration

- docker/keycloak/extensions-7.6/services/pom.xml
- docker/keycloak/extensions-7.6/services/src/main/java/com/github/bcgov/keycloak/authenticators/UserSessionRemover.java
- docker/keycloak/extensions-7.6/services/src/main/java/com/github/bcgov/keycloak/authenticators/UserSessionRemoverFactory.java
- docker/keycloak/extensions-7.6/services/src/main/resources/META-INF/services/org.keycloak.authentication.AuthenticatorFactory
- docker/keycloak/extensions-7.6/services/src/test/java/com/github/bcgov/keycloak/authenticators/UserSessionRemoverTest.java
Add authenticator to remove sessions based on client check. Basic logic is if I have an active session with any client other than the one I am currently authenticating with, remove my user session. If my session is only linked to the current client, let it be. 
I spent some time updating the unit test setup, for the new tests I needed to bump Mockito so that mocking static methods was possible, and the maven-surefire-plugin was needed to use jupiter which has some nice annotations (mainly @BeforeEach).
The new unit test dependencies have `<scope>test</scope>` so they will get excluded from the production build. Just mentioning this because I am not as familiar with the Java build process so pointing it out for review.
> chore: authenticator

- .github/workflows/publish-devhub.yml
Updated the [publish-devhub.yml](https://github.com/bcgov/sso-keycloak/blob/dev/.github/workflows/publish-devhub.yml) file to make use of the [devhub-techdocs-publish](https://github.com/bcgov/devhub-techdocs-publish) GitHub action.
> Update to use bcgov/devhub-techdocs-publish GitHub action

- helm/kc-cron-job/templates/network-policy.yaml
- helm/kc-cron-job/values-c6af30-tools.yaml
In the e4ca1d-tools/eb75ad-tools namespaces there is a network policy "allow-same-namespace", pretty sure this was added manually not from any helm chart, the only reference I found to it was in the metabase charts readme but just saying to ensure they exist . It is needed for the cronjob pods in the tools namespace to talk to the patroni instance there, so I added a policy to the kc-cron-job chart to cover this so it would be in helm. I tightened it up a bit to just select patroni and the cron-job-pods instead of all pods in the namespace, figure if we're allowing more traffic later pods can have their own network policies.
This also enables the cronjobs in the c6 helm chart to test them out, they seem to be running well there.
> chore: network policy

- .tool-versions
- docker/keycloak/configuration/24/quarkus.properties
- docker/keycloak/extensions-24/services/pom.xml
- docker/keycloak/extensions-24/services/src/main/java/com/github/bcgov/keycloak/authenticators/UserSessionRemover.java
- docker/keycloak/extensions-24/services/src/test/java/com/github/bcgov/keycloak/authenticators/UserSessionRemoverTest.java
The DC flow was finding existing client sessions during the authentication flow using `userSessionProvider.getActiveClientSessionStats(context.getRealm(), false);`, which was returning all sessions.  Switching this to the `userSessionModel.getAuthenticatedClientSessions();` method which is scoped to the user.
I also updated the logging setup in the properties file, the env vars were not overriding by default
> fix: user-session remover

- wiki/Identity-Provider-Attribute-Mapping.md
add note to why display name is duplicated, see below for render (not including bcgov theme):
> docs: clarify display name

- docker/kc-cron-job/remove-inactive-idir-users.js
- docker/kc-cron-job/yarn.lock
- Fix delete limit going slightly over
- Switch to BCeID Web Service (kept the function for ms graph so we can switch back easily if needed)
- Changed the limit in prod from 250 total (50 in 5 runners) to 50 in total (10 in 5 runners), open to discussion on that being too low I think we rarely see more than 50 in a night though, and it would just catch up the next day if there are more
> fix: deletion limit

- helm/kc-cron-job/templates/cron-remove-inactive-users.yaml
add missing vars for bceid service in helm
> chore: missing env vars

- wiki/Our-Partners-the-Identity-Providers.md
Committing SSOTEAM---1872 for BCSC section update
> Committing SSOTEAM---1872 for BCSC section update

- wiki/Our-Partners-the-Identity-Providers.md
> feat:Adding changes for SSOTEAM-1872

- .github/workflows/unit-test.yml
- docker/kc-cron-job/.dockerignore
- docker/kc-cron-job/__tests__/remove-inactive-idir-users.test.js
- docker/kc-cron-job/helpers.js
- docker/kc-cron-job/remove-inactive-idir-users.js
- docker/kc-cron-job/utils/bceid-webservice.js
- Include the environment in calls to the CSS app
- Fixed an off by one error on the max deletions (>= instead of >) 
- Moved some of the idir job dependencies into modules to make unit testing simpler. i.e the bceid-webservice functions into a util file, and keycloak ones into the helpers file since it contained the other keycloak stuff already.
> fix: env in payload
