.tool-versions, docker/kc-cron-job/event-logs.js, docker/kc-cron-job/zip-logs.js, helm/kc-cron-job/templates/cron-event-logs.yaml
=> chore: logging

docker/kc-cron-job/event-logs.js, docker/kc-cron-job/zip-logs.js, helm/kc-cron-job/migration.sql, helm/kc-cron-job/templates/cron-event-logs.yaml
remove trigger, run pg function, fix unfound directory
=> chore: remove trigger

helm/kc-cron-job/templates/cron-event-logs.yaml, scripts/client-mappers/azure-idir.json, scripts/idp-mappers/idir-azure.json, scripts/meta/idp-realms.json
=> chore: azure idir

scripts/idp-mappers/azure-idir.json, scripts/keycloak-link-idp.js, scripts/meta/idp-realms.json
=> fix: script

helm/keycloak/templates/deployment.yaml, helm/keycloak/values-b861c7-test-4.yaml, helm/keycloak/values-b861c7-test-5.yaml, helm/keycloak/values-b861c7-test-6.yaml, scripts/helpers.js, scripts/keycloak-core.js, scripts/keycloak-import-idir-users.js, scripts/keycloak-migrate-idir-users.js
- kc script to migrate one `IDIR` parent realm users to another.
- kc script to import `IDIR` users from parent realm to standard realm.
=> feat: add kc script to migrate/import idir users

helm/keycloak/templates/deployment.yaml, helm/keycloak/values-b861c7-tools.yaml, helm/patroni/Makefile, helm/patroni/templates/job-appdb.yaml, helm/patroni/values-b861c7-tools-sso-patroni.yaml, helm/patroni/values.yaml
- add a k8s job to run after on `patroni` creation to create appdb and appuser.
=> feat: add appuser in patroni helm chart

helm/keycloak/values-c6af30-prod.yaml, helm/keycloak/values-c6af30-test.yaml, helm/keycloak/values-eb75ad-dev.yaml, helm/keycloak/values-eb75ad-prod.yaml, helm/keycloak/values-eb75ad-test.yaml, helm/patroni/values-c6af30-dev-sso-patroni.yaml, helm/patroni/values-c6af30-prod-sso-patroni.yaml, helm/patroni/values-c6af30-test-sso-patroni.yaml, helm/patroni/values-eb75ad-dev-sso-patroni.yaml, helm/patroni/values-eb75ad-prod-sso-patroni.yaml, helm/patroni/values-eb75ad-test-sso-patroni.yaml
This fixes the database login credential in dev test and prod in sandbox and production gold.  
The database backup verifcation container can now function, though the backup restore in gold is still not working
=> Gold cred 1130

helm/metabase/README.md, helm/metabase/values-c6af30-tools.yaml
=> feat: metabase

docker/keycloak/extensions-7.5-9/themes/src/main/resources/theme/bcgov-idp-stopper/login/theme.properties, docker/keycloak/extensions-7.5-9/themes/src/main/resources/theme/bcgov/login/template.ftl, helm/helpers.sh, helm/keycloak/deploy-eb75ad-dev-gold.sh, helm/keycloak/deploy-eb75ad-prod-gold.sh, helm/keycloak/deploy-eb75ad-test-gold.sh, helm/keycloak/values-b861c7-test-4.yaml, helm/keycloak/values-b861c7-test-5.yaml, helm/keycloak/values-b861c7-test-6.yaml, scripts/keycloak-populate-github-ids.js, scripts/role-migrations/groups-clientroles.js, terraform/gold/main.tf, terraform/golddr/main.tf
- deploy `service accounts` in gold cluster namespaces.
- deploy keycloak new image to use `client's name` as the login title.
- check Kube endpoint before running helm charts.
=> chore: minor tweks

helm/keycloak/deploy-eb75ad-prod-golddr.sh, helm/keycloak/values-golddr-eb75ad-prod.yaml
=> feat: golddrhelm

.github/workflows/set-dr-active.yml, helm/keycloak/transition-scripts/deploy-golddr-active.sh
=> Set dr active

docker/keycloak/extensions-7.5-9/services/src/main/java/com/github/bcgov/keycloak/broker/oidc/CustomOIDCIdentityProviderFactory.java, docker/keycloak/extensions-7.5-9/services/src/main/java/com/github/bcgov/keycloak/social/github/CustomGitHubIdentityProvider.java, docker/keycloak/extensions-7.5-9/services/src/main/java/com/github/bcgov/keycloak/social/github/CustomGitHubIdentityProviderFactory.java, docker/keycloak/extensions-7.5-9/services/src/main/java/com/github/bcgov/keycloak/social/github/CustomGitHubUserAttributeMapper.java, docker/keycloak/extensions-7.5-9/services/src/main/resources/META-INF/services/org.keycloak.broker.provider.IdentityProviderMapper, docker/keycloak/extensions-7.5-9/services/src/main/resources/META-INF/services/org.keycloak.broker.social.SocialIdentityProviderFactory, docker/keycloak/extensions-7.5-9/themes/src/main/resources/META-INF/keycloak-themes.json, docker/keycloak/extensions-7.5-9/themes/src/main/resources/theme/base/admin/resources/partials/realm-identity-provider-github-custom-ext.html, docker/keycloak/extensions-7.5-9/themes/src/main/resources/theme/base/admin/resources/partials/realm-identity-provider-github-custom.html, docker/keycloak/extensions-7.5-9/themes/src/main/resources/theme/base/admin/resources/partials/realm-identity-provider-oidc-custom.html, localdev/Makefile, localdev/README.md
- custom `oidc idp provider` placehoder that can be used in the future.
- custom `github idp provider` to allow the target org only.
=> Lc wmgj ga

docker/keycloak/configuration/standalone-openshift-7.6.xml, docker/keycloak/original/standalone-openshift-7.6.xml
- configure `db migration strategy` to auto-update as Keycloak version upgrading is failing in sandbox.
=> chore: update configuration for 7.6

helm/backup-storage/values-3d5c3f-dev-patroni-backup-storage.yaml, helm/backup-storage/values-3d5c3f-prod-sso-backup.yaml, helm/backup-storage/values-6d70e7-test-patroni-backup-storage.yaml, helm/keycloak/values-3d5c3f-dev.yaml, helm/keycloak/values-3d5c3f-prod.yaml, helm/keycloak/values-6d70e7-test.yaml, helm/silver-patroni/README.md, helm/silver-patroni/values-3d5c3f-dev.yaml, helm/silver-patroni/values-3d5c3f-prod.yaml, helm/silver-patroni/values-6d70e7-test.yaml
This creates the new test postgres deployment and the sandbox deployments
=> Patroni spike

.github/ISSUE_TEMPLATE/silver-custom-gold-custom-request.yml
requesting approval so i can have updated intake form
=> Zsamji patch 3

docker/keycloak/extensions-7.6/services/src/main/java/com/github/bcgov/keycloak/authenticators/BrokeredIdentityContext.java, docker/keycloak/extensions-7.6/services/src/main/java/com/github/bcgov/keycloak/authenticators/UserAttributeAuthenticator.java, docker/keycloak/extensions-7.6/services/src/main/java/com/github/bcgov/keycloak/authenticators/UserAttributeAuthenticatorFactory.java, docker/keycloak/extensions-7.6/services/src/main/java/com/github/bcgov/keycloak/social/github/CustomGitHubIdentityProvider.java, docker/keycloak/extensions-7.6/services/src/main/resources/META-INF/services/org.keycloak.authentication.AuthenticatorFactory, docker/keycloak/extensions-7.6/themes/src/main/resources/theme/base/admin/resources/partials/realm-identity-provider-github-custom-ext.html
- update Keycloak extension to pass `org_verified` flag.
- add authentication to validate the user with its attribute.
=> chore: update github idp extension

helm/backup-storage/values-6d70e7-prod-patroni-backup-storage.yaml
increase the PVC size to resolve 60 PVC alert
=> chore: bumpPVC

docker/keycloak/extensions-7.6/services/src/main/java/com/github/bcgov/keycloak/protocol/oidc/mappers/ClaimOmitterMapper.java, docker/keycloak/extensions-7.6/services/src/main/resources/META-INF/services/org.keycloak.protocol.ProtocolMapper, docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov-idp-stopper/login/login.ftl, docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov/login/resources/css/styles.css
- update the theme to move info tooltip icon inside buttons
- add a custom mapper to omit claims by the selected IDPs
=> feat: add claim omitter mapper

.github/ISSUE_TEMPLATE/silver-custom-gold-custom-request.yml
just need to have the yaml file updated. hope i did this right :)
=> update list of silver realms to still create

docker/maintenance-page/Dockerfile
=> chore: version

docker/keycloak/Dockerfile-7.6, docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov-idp-stopper-no-header-title/login/theme.properties, docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov-idp-stopper/login/theme.properties, docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov-sentence-case/login/theme.properties, docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov/login/resources/css/styles-20221128.css, docker/keycloak/extensions-7.6/themes/src/main/resources/theme/bcgov/login/template.ftl
add theme for sentence case title
=> chore: theme

wiki/Useful-References.md
added link to tech docs for dev clients
=> chore: added link

docker/kc-cron-job/remove-dc-users.js, docker/kc-cron-job/remove-inactive-idir-users.js
1.Both remove-inactive-users and remove-dc-users scripts now run all the jobs irrespective of any failures and post the results to rocket chat
2. The rocket chat notification has been updated as well
=> fix: fixed RC notifs and DC users only removed from STD realm

wiki/Our-Partners-the-Identity-Providers.md
=> chore: updated dc text

.github/workflows/publish-devhub.yml, mkdocs.yml
Removing the deprecated mermaid dependency
=> fix: devhub action

docker/keycloak/configuration/24/keycloak.conf
=> chore: log config

scripts/keycloak-switch-user-integration-role.js
script to add a new role to all users with an old role (roles given via cli)
=> chore: role migration

scripts/keycloak-switch-user-integration-role.js
The users request defaults to 100. Updating this to handle 100 per prompt, which is good for reduced rate of requests too
=> chore: pagination

docker/kc-cron-job/remove-inactive-idir-users.js
remove invalid property override
=> chore: remove override

wiki/Our-Partners-the-Identity-Providers.md
committing new changes due to existing issues
=> feat: commiting new changes

wiki/Our-Partners-the-Identity-Providers.md
adding integration with standard service as it was missed
=> feat: adding integration with standard service

docker/kc-cron-job/utils/bceid-webservice.js
fix missing imports that were stubbed in tests
=> fix: imports

wiki/Alerts-and-Us.md
=> chore: newsletter link

.github/workflows/publish-image-keycloak-benchmark.yml, benchmark/Makefile, benchmark/README.md, docker/keycloak/Dockerfile-24-perf, k6/k6-runner/Makefile
Updating documentation and creating a RHBK 24 benchmark image
=> chore: create a keycloak 24 benchmark image

docker/otp-provider/README.md, docker/otp-provider/package.json, docker/otp-provider/src/controllers/auth-controller.ts, docker/otp-provider/src/events.ts, docker/otp-provider/src/modules/sequelize/migrations/001_create_client_config_table.ts, docker/otp-provider/src/modules/sequelize/migrations/014_create_grant_table.ts, docker/otp-provider/src/modules/sequelize/migrations/015_create_back_channel_auth_request_table.ts, docker/otp-provider/src/modules/sequelize/models.ts, docker/otp-provider/src/routes.ts, docker/otp-provider/src/server.ts, docker/otp-provider/src/utils/helpers.ts, docker/otp-provider/yarn.lock
- Updates to content security policies to allow secure login and RP-init logouts
- Added two new tables to account for latest version of oidc provider
- Resolved minor bugs
- Client allowed with expected web origins
- Removed express rate limit as it is not useful having API gateway and load balancer infront of the app
=> feat: updated content security policies and fixed minor bugs

docker/otp-provider/src/client/otp.ts
disable continue button while form submitting
=> chore: disable button

.github/ISSUE_TEMPLATE/silver-custom-gold-custom-request.yml, scripts/custom-realm-users/README.md, wiki/Our-Partners-the-Identity-Providers.md, wiki/SSO-Onboarding.md, wiki/Useful-References.md, wiki/What-is-Keycloak-at-BC-Government.md, wiki/index.md
update app links to new url. Leaving in draft since this will deploy on merge, so is waiting for migration first
=> chore: app links

.github/workflows/publish-otp-provider-image.yml
Add missing quotes on new variables in ci pipeline
=> fix: gh actions

.github/workflows/publish-otp-provider-image.yml, docker/otp-provider/terraform/ecs.tf, docker/otp-provider/terraform/variables.tf
add prod deployment pipeline for otp server
=> chore: prod deploy

docker/otp-provider/e2e/otp.spec.ts, docker/otp-provider/src/client/otp.ts, docker/otp-provider/src/client/shared.ts, docker/otp-provider/src/client/signin.ts
prevent form resubmission and improve backspace function
=> chore: otp ux
